config/routes.rb
Rails.application.routes.draw do

  resources :mypages, only: [:index, :show, :destroy] do
    collection do
      get 'payment_method'
      get 'payment_method/card', to: 'mypages#card_new'
    end
  end

  get 'users', to: 'users#logout'

  resources :categories, only: [:show]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'identifications', to: 'users/registrations#new_identification'
    post 'identifications', to: 'users/registrations#create_identification'

    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :purchases, only: [:index, :create] do
    collection do
      get  'payment_method'
      get  'address'
      get  ':id', to: 'purchases#index'
      post 'pay', to: 'purchases#pay'
      post 'pay/:id', to: 'purchases#pay'
      post 'paymethod_selected'
      get  'payment_method/:id', to: 'purchases#payment_method'
    end
  end

  resources :tops, only: :show
  resources :products, only: [:index]
  resources :registrations, only: [:index]
  root 'products#index'

  resources :products, except: :destroy do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :card, only: :new do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'pay/:id', to: 'card#pay'
      post 'delete', to: 'card#delete'
      get 'card/new/:id', to: 'card#new'
    end
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!

  require 'payjp'

  def index
    @product = Product.includes(:images).find(params[:id])
    @address = Address.find(current_user.id)
    @card_selected = PaymentSelected.find_by(user_id: current_user.id)

    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

    if @card_selected.card_selected.to_i != 0
      @card_selected.card.customer_id
      card = Payjp::Customer.retrieve(@card_selected.card.customer_id)
      @card_info = card.cards.data[0]
    end
  end

  def pay
    @product = Product.find(params[:id])
    @card_selected = PaymentSelected.find_by(user_id: current_user.id)

    if @card_selected.card.blank?
      flash[:notice] = 'クレジットカードで購入してください。'
      redirect_to controller: :purchases, action: :index, id: @product.id
    else

      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

      Payjp::Charge.create(
        amount: @product.price,
        customer: @card_selected.card.customer_id,
        currency: 'jpy',
      )

      @product.buyer_id = current_user.id
      @product.save

      redirect_to root_path
    end
  end

  def payment_method
    @card_selected = PaymentSelected.find_by(user_id: current_user.id)
    cards = Card.where(user_id: current_user.id)

    @cards_info = []

    cards.each do |card|
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      payjp_card = Payjp::Customer.retrieve(card.customer_id)
      @cards_info << payjp_card.cards.retrieve(card.card_id)
    end

    @payment_selected = PaymentSelected.new
  end

  def paymethod_selected
    @card_selected = PaymentSelected.find_by(user_id: current_user.id)
    @card_selected.update(selected_params)

    if @card_selected.card_selected == "0"
      @card_selected.card_id = ""
      @card_selected.save
    else
      cards = Card.where(user_id: current_user.id)
      @card_selected.card_id = cards[@card_selected.card_selected.to_i - 1].id
      @card_selected.save
    end

    if @card_selected.id_path.blank?
      redirect_to payment_method_mypages_path
    else
      redirect_to purchases_path(id: @card_selected.id_path)
    end
  end

  private

  def selected_params
    params.require(:payment_selected).permit(:card_selected, :id_path)
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form-header.html.haml
.form-header
  .header__btn
    =link_to image_tag("material/logo/logo.png", width: "200px", height: "50px"), root_path, class: 'black-logo'

app/views/purchases/_form-info.html.haml
.form-info
  %ul.menu
    %li.menu--list
    = link_to "プライバシーポリシー", "#", class: "menu--list"
    %li.menu--list
    = link_to "FURIMA利用規約", "#", class: "menu--list"
    %li.menu--list
    = link_to "特許商取引に関する表記", "#", class: "menu--list"
  .icon
    =link_to image_tag("material/logo/logo-white.png", width: "160px", height: "40px"), root_path, class: 'white-logo'
  %p.copyright © FURIMA

app/views/purchases/_payment_method.html.haml
.card
  %section.section-top
    %h2.title 支払い方法
  .payments
    = form_for @payment_selected, :url => url_for(:controller => 'purchases', :action => 'paymethod_selected') do |f|
      .atm
        .contents
          .mark
            = f.radio_button :card_selected, "0", class: "check-img", checked: @card_selected.card_selected.to_i == 0
          .pay-atm
            %p.name コンビニ/ATM払い
            %p.fee （手数料¥100）
      - @cards_info.each.with_index(1) do |card_info, i|
        .credit-card
          .current-user
            .current-user__info
              .credit-check
                = f.radio_button :card_selected, i, class: "credit-check__button", checked: @card_selected.card_selected.to_i == i
              .credit-info
                %p.number
                  = "************" + card_info.last4
                %p.expiration
                  - exp_month = card_info.exp_month.to_s
                  - exp_year = card_info.exp_year.to_s.slice(2,3)
                  = "有効期限 " + exp_month + " / " + exp_year
                .image
                  - case card_info.brand
                  - when "Visa"
                    = image_tag 'material/card-logo/logo_visa.gif', class: 'img'
                  - when "MasterCard"
                    = image_tag 'material/card-logo/logo_mastercard.gif', class: 'img'
                  - when "JCB"
                    = image_tag 'material/card-logo/credit-card-logo-jcb.gif', class: 'img'
                  - when "American Express"
                    = image_tag 'material/card-logo/amex-logomark.gif', class: 'img'
                  - when "Diners Club"
                    = image_tag 'material/card-logo/diners-logomark.gif', class: 'img'
                  - when "Discover"
                    = image_tag 'material/card-logo/discover-logomark.gif', class: 'img'
            .current-user__delete
              .current-user__delete--btn 削除する
      .add-card.add-border
        - if params[:id].blank?
          = link_to " クレジットカードを追加", payment_method_card_mypages_path, class: "add-card--btn", "data-turbolinks": false
        - else
          = link_to " クレジットカードを追加", new_card_path(id: params[:id].to_i), class: "add-card--btn", "data-turbolinks": false
      .button
        .button__enter
          = f.hidden_field :id_path, value: params[:id]
          = f.submit "選択した支払い方法を使う", class: "enter-button"
          = image_tag 'material/ajax-load.gif', class: "icon_load"
        - if params[:id].blank?
          = link_to "支払い方法について >", "#", class: "about-paymethod"
        - else
          = link_to "もどる", purchases_path(id: params[:id].to_i), class: "back-btn"

app/views/purchases/address.html.haml
= render "purchases/form-header"
.form-wrapper
  .section
    %section.head
      %h2.head--title 発送元・お届け先住所入力
    %form.form-addresses
      = form_with url: "#", local: true do |f|
        .contents
          %section#top-group.group
            %label.group--name お名前
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）山田", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
              = f.text_field :test, placeholder: "例）彩", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
          %section.group
            %label.group--name お名前カナ
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）ヤマダ", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
              = f.text_field :test, placeholder: "例）アヤ", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
          %section.group
            %label.group--name 郵便番号
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）123-4567", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
          %section.group
            %label.group--name 都道府県
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）123-4567", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
                %li.error-message--text フォーマットが不適切です
          %section.group
            %label.group--name 市区町村
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）横浜市緑区", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
          %section.group
            %label.group--name 番地
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）青山1-1-1", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
          %section.group
            %label.group--name 建物名
            %span.group--any 任意
            .input
              = f.text_field :test, placeholder: "例）柳ビル103", class: "input--style"
          %section.group
            %label.group--name 電話
            %span.group--any 任意
            .input
              = f.text_field :test, placeholder: "例）09012345678", class: "input--style"
          .change
            = link_to "変更する", purchases_path, class: "change__btn"
= render "purchases/form-info"

app/views/purchases/edit.html.haml
= render "purchases/form-header"
.form-wrapper
  .section
    %section.head
      %h2.head--title 発送元・お届け先住所入力
    %form.form-addresses
      = form_with url: "#", local: true do |f|
        .contents
          %section#top-group.group
            %label.group--name お名前
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）山田", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
              = f.text_field :test, placeholder: "例）彩", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
          %section.group
            %label.group--name お名前カナ
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）ヤマダ", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
              = f.text_field :test, placeholder: "例）アヤ", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
          %section.group
            %label.group--name 郵便番号
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）123-4567", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
          %section.group
            %label.group--name 都道府県
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）123-4567", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
                %li.error-message--text フォーマットが不適切です
          %section.group
            %label.group--name 市区町村
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）横浜市緑区", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
          %section.group
            %label.group--name 番地
            %span.group--required 必須
            .input
              = f.text_field :test, placeholder: "例）青山1-1-1", class: "input--style"
              %ul.error-message
                %li.error-message--text 入力してください
          %section.group
            %label.group--name 建物名
            %span.group--any 任意
            .input
              = f.text_field :test, placeholder: "例）柳ビル103", class: "input--style"
          %section.group
            %label.group--name 電話
            %span.group--any 任意
            .input
              = f.text_field :test, placeholder: "例）09012345678", class: "input--style"
          .change
            = link_to "変更する", purchases_path, class: "change__btn"
= render "purchases/form-info"

app/views/purchases/index.html.haml
= render "purchases/form-header"
.form-wrapper
  .section
    %section.content
      %h2.content__check 購入内容の確認
    %section.product
      .detail
        .image
          = image_tag @product.images.first.image.url, class: "product-img"
        .product-info
          %p.product-info__name
            = @product.name
          .product-info__price
            %span.product-info__price--tax 送料込み（税込）
            %span.product-info__price--number
              = "¥" + @product.price.to_s
    %section.pay-fee
      .total
        %p.total__font 支払金額
        %p.total__price
          = "¥" + @product.price.to_s
    - if @card_selected.card_selected.to_i == 0
      %section.pay-method
        .payment
          .payment-top
            %h3.title 支払い方法
            = link_to "変更します >", payment_method_purchases_path(id: @product.id), class: "change-btn"
          .payment__method
            %p.credit-card コンビニ/ATM払い
            %p.fee (手数料¥100)
    - else
      %section.pay-method
        .payment
          .payment-top
            %h3.title 支払い方法
            = link_to "変更します >", payment_method_purchases_path(id: @product.id), class: "change-btn"
          .payment__method
            %p.credit-card クレジットカード
            %p.number
              = "************" + @card_info.last4
            %p.expiration
              - exp_month = @card_info.exp_month.to_s
              - exp_year = @card_info.exp_year.to_s.slice(2,3)
              = "有効期限 " + exp_month + " / " + exp_year
    %section.address
      .address__user
        .address__user--top
          %h3.title 配送先
        .address-font
          %p.address-font--postcode
            = @address.postcode
          %p.address-font--city
            = @address.prefecture.name + " " + @address.city + " " + @address.block + " " + @address.building
          %p.address-font--name
            = @address.last_name + @address.first_name
    %section.buy-button
      .btn
        %button.btn--purchase 購入する
    %section.buy-button-modal
      .sign_modal
        .content-text
          購入確認画面
        .imageg
          = image_tag @product.images.first.image.url, class: "product-img"
        .price
          %p.total__price
            = "¥" + @product.price.to_s
        .last-confirmation
          .cancelBtn
            .cancel-button キャンセル
          .buyBtn
            = form_tag(pay_purchases_path(id: @product.id)) do
              %button.byModal-button 購入確定
= render "purchases/form-info"

app/views/purchases/new.html.haml
= render "purchases/form-header"
.form-wrapper
  = render "purchases/pay-method"
= render "purchases/form-info"

app/views/purchases/pay-method.html.haml
= render "purchases/form-header"
.form-wrapper
  = render "purchases/pay-method"
= render "purchases/form-info"

app/views/purchases/payment_method.html.haml
.nice
  = render "purchases/form-header"
  .form-wrapper
    .section
      = render "purchases/payment_method"
  = render "purchases/form-info"