config/routes.rb
Rails.application.routes.draw do

  resources :mypages, only: [:index, :show, :destroy] do
    collection do
      get 'payment_method'
      get 'payment_method/card', to: 'mypages#card_new'
    end
  end

  get 'users', to: 'users#logout'

  resources :categories, only: [:show]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'identifications', to: 'users/registrations#new_identification'
    post 'identifications', to: 'users/registrations#create_identification'

    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :purchases, only: [:index, :create] do
    collection do
      get  'payment_method'
      get  'address'
      get  ':id', to: 'purchases#index'
      post 'pay', to: 'purchases#pay'
      post 'pay/:id', to: 'purchases#pay'
      post 'paymethod_selected'
      get  'payment_method/:id', to: 'purchases#payment_method'
    end
  end

  resources :tops, only: :show
  resources :products, only: [:index]
  resources :registrations, only: [:index]
  root 'products#index'

  resources :products, except: :destroy do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :card, only: :new do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'pay/:id', to: 'card#pay'
      post 'delete', to: 'card#delete'
      get 'card/new/:id', to: 'card#new'
    end
  end

end

app/models/Shipping.rb
class Shipping < ActiveHash::Base
  self.data = [
    {id: 1, name: "1日〜2日で発送"},
    {id: 2, name: "2日〜3日で発送"},
    {id: 3, name: "4日〜7日で発送"},
  ]

  include ActiveHash::Associations
  has_many :products
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  validates :postcode, :city, :block, :prefecture_id, :last_name, :first_name, :last_name_kana, :first_name_kana, presence: true
  validates :last_name, :first_name, format: {with: /\A[ぁ-んァ-ン一-龥]/}
  validates :last_name_kana, :first_name_kana, format: { with:  /\A[ァ-ヶー－]+\z/}
  validates :postcode, format: {with: /\A[0-9]{3}-[0-9]{4}\z/}
  validates :phone_number, format: {with: /\A\d{10,11}\z/}, allow_blank: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/card.rb
class Card < ApplicationRecord
  has_one :payment_selected
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/identification.rb
class Identification < ApplicationRecord
  belongs_to :user, optional: true
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, presence: true
  validates :last_name, :first_name, format: {with: /\A[ぁ-んァ-ン一-龥]/}
  validates :last_name_kana, :first_name_kana, format: { with:  /\A[ァ-ヶー－]+\z/}
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product

  validates :image, :product, presence: true
  validates_presence_of :product
end

app/models/payment_selected.rb
class PaymentSelected < ApplicationRecord
  belongs_to :user
  belongs_to :card, optional: true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]

  include ActiveHash::Associations
  has_many :products
  has_many :addresses
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :saler, class_name: "User"
  belongs_to :category
  has_many :images, dependent: :destroy
  has_one :brand, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :brand, allow_destroy: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :status
  belongs_to_active_hash :shippingcost
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shipping

  validates :name, presence: true
  validates :images, presence: { message: '商品画像がありません'}
  validates :category, presence: { message: 'カテゴリが選択されていません'}
  validates :detail, presence: true
  validates :status_id, presence: true
  validates :prefecture_id, presence: true
  validates :shippingcost_id, presence: true
  validates :shipping_id, presence: true
  validates :price, presence: true

end

app/models/shipping_cost.rb
class Shipping_cost < ActiveHash::Base
  include ActiveHash::Associations
  has_many :products
  self.data = [
    {id: 1, name: "送料込み（出品者負担）"},
    {id: 2, name: "着払い（購入者負担）"},
  ]
end

app/models/shippingcost.rb
class Shippingcost < ActiveHash::Base
  include ActiveHash::Associations
  has_many :products
  self.data = [
    {id: 1, name: "送料込み（出品者負担）"},
    {id: 2, name: "着払い（購入者負担）"},
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    {id: 1, name: "新品、未使用"},
    {id: 2, name: "未使用に近い"},
    {id: 3, name: "目立った傷や汚れなし"},
    {id: 4, name: "やや傷や汚れあり"},
    {id: 5, name: "傷や汚れあり"},
    {id: 6, name: "全体的に状態が悪い"}
  ]

  include ActiveHash::Associations
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  validates :nickname ,presence: true
  validates :email, format: { with:  /\A\S+@\S+\.\S+\z/}
  has_one :identification
  has_one :address
  has_one :payment_selected
  has_many :products
end 

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @saler_products = Product.where(saler_id: current_user.id)
    @buyer_products = Product.where(buyer_id: current_user.id)
    @user = User.find_by(id: current_user.id)
  end

  def show
    if user_signed_in?
      @selected_product = Product.includes(:images).find(params[:id])
      @categories = Category.all
    else
      redirect_to new_user_session_path
    end
  end

  def payment_method
    @card_selected = PaymentSelected.find_by(user_id: current_user.id)
    cards = Card.where(user_id: current_user.id)

    @cards_info = []

    cards.each do |card|
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      payjp_card = Payjp::Customer.retrieve(card.customer_id)
      @cards_info << payjp_card.cards.retrieve(card.card_id)
    end

    @payment_selected = PaymentSelected.new
  end

  def destroy
    delete_product = Product.find(params[:id])
    delete_product.destroy
    redirect_to mypages_path
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/mypages/_footer.html.haml
.tesuto
  部分テンプレートで差込

app/views/mypages/_header.html.haml
.tesuto
  部分テンプレートで差込

app/views/mypages/_side_bar.html.haml
.mypage-left
  .mypage-left__content
    = link_to mypages_path, class: "button" do
      .text-box
        .text-box__left
          マイページ
        .text-box__right
          = icon("fas", "chevron-right")
    = link_to "#", class: "button" do
      .text-box
        .text-box__left
          いいね一覧
        .text-box__right
          = icon("fas", "chevron-right")
    = link_to new_product_path, class: "button" do
      .text-box
        .text-box__left
          出品する
        .text-box__right
          = icon("fas", "chevron-right")
    = link_to "#", class: "button" do
      .text-box
        .text-box__left
          下書き一覧
        .text-box__right
          = icon("fas", "chevron-right")
    = link_to "#", class: "button" do
      .text-box
        .text-box__left
          出品した商品−出品中
        .text-box__right
          = icon("fas", "chevron-right")
    = link_to "#", class: "button" do
      .text-box
        .text-box__left
          出品した商品−売却済み
        .text-box__right
          = icon("fas", "chevron-right")
    = link_to "#", class: "button" do
      .text-box
        .text-box__left
          購入した商品−取引中
        .text-box__right
          = icon("fas", "chevron-right")
    = link_to "#", class: "button" do
      .text-box
        .text-box__left
          購入した商品−過去の取引
        .text-box__right
          = icon("fas", "chevron-right")
    = link_to "#", class: "button" do
      .text-box
        .text-box__left
          評価一覧
        .text-box__right
          = icon("fas", "chevron-right")
  .middle-text
    設定
  .mypage-left__content
    = link_to "#", class: "button" do
      .text-box
        .text-box__left
          発送元・お届け先住所変更
        .text-box__right
          = icon("fas", "chevron-right")
    = link_to payment_method_mypages_path, class: "button" do
      .text-box
        .text-box__left
          支払い方法
        .text-box__right
          = icon("fas", "chevron-right")
    = link_to "#", class: "button" do
      .text-box
        .text-box__left
          メール/パスワード
        .text-box__right
          = icon("fas", "chevron-right")
    = link_to users_path, class: "button" do
      .text-box
        .text-box__left
          ログアウト
        .text-box__right
          = icon("fas", "chevron-right")

app/views/mypages/card_new.html.haml
= render 'products/head_tmp'
.mypage-wrapper
  .main-body
    = render partial: "side_bar"
    = render 'card/card_new'
= render 'products/footer_tmp'

app/views/mypages/index.html.haml
=render partial: "products/head_tmp" 
.mypage-wrapper
  .main-body
    =render partial: "side_bar"
    .mypage__right-main
      .main-box
        = image_tag "user-bg.jpg", size: "700x200"
        .user
          .user__img
            = image_tag "material/icon/smile-white.png", size: "50x50", class: "user__img--img"
          .user-name
            = @user.nickname
          .info-box
            .info-box__left
              .info-box__left--text
                評価
              .info-box__left--num
                0
            .info-box__right
              .info-box__right--text
                出品数
              .info-box__right--num
                = @saler_products.length
      .menu-head__tab 購入した商品
      .menu
        .menu__list.active
          #about.menu__item 過去の取引商品
        .menu__list
          #about.menu__item 出品した商品
      .menu__product
        .display.products_info.second-display
          -if @buyer_products.length == 0
            = image_tag "logo-white.png", size: "250x80", class:"content-image"
            %li.content.show
              過去の取引はありません
          -else 
            - @buyer_products.each do |buyer_product|
              = link_to product_path(buyer_product.id), class: "saler-product" do
                .product-item
                  = image_tag buyer_product.images[0].image.url, size: "50x50"
                  .produit-details
                    %p.name
                      = buyer_product.name
                    .mypage-item-status
                      取引完了 
                .menu-myitem__right
                  = icon("fas", "chevron-right")
        .display.products_info
          -if @saler_products.length == 0
            = image_tag "logo-white.png", size: "250x80", class:"content-image"
            %li.content.show
              出品中の商品はありません
          -else 
            - @saler_products.each do |saler_product|
              = link_to mypage_path(saler_product.id), class: "saler-product" do
                .product-item
                  = image_tag saler_product.images[0].image.url, size: "50x50"
                  .produit-details
                    %p.name
                      = saler_product.name
                    -if saler_product.buyer_id.blank?
                      .mypage-item-status
                        出品中
                    -else
                      .mypage-item-status
                        取引完了
                .menu-myitem__right
                  = icon("fas", "chevron-right")     
=render partial: "products/footer_tmp"

app/views/mypages/payment_method.html.haml
= render 'products/head_tmp'
.mypage-wrapper
  .main-body
    = render partial: "side_bar"
    = render 'purchases/payment_method'
= render 'products/footer_tmp'

app/views/mypages/show.html.haml
.show-top
  = render 'products/head_tmp'

.show-wrapper
  .show-main
    .contents
      .top-content
        .product
          %h2.product__name
            = @selected_product.name
          .product__body
            %ul
              %li
                = image_tag @selected_product.images[0].image.url
                %ul
                  - @selected_product.images.each_with_index do |productimage|
                    %li
                      = image_tag productimage.image.url
          .product__price
            %span
              ¥
              = @selected_product.price
            .product__price--detail
              (税込)送料込み
          .product__description
            = @selected_product.detail
          .table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td
                    = @selected_product.saler.nickname
                %tr
                  %th カテゴリー
                  %td
                    - @categories.each do |grandchildren|
                      - if @selected_product.category_id == grandchildren.id
                        = link_to category_path(grandchildren.parent.parent.id) do
                          = grandchildren.parent.parent.name
                          %br
                        = link_to category_path(grandchildren.parent.id) do
                          = grandchildren.parent.name
                          %br
                        = link_to category_path(grandchildren.id) do
                          = grandchildren.name
                          %br
                %tr
                  %th ブランド
                  %td
                    = @selected_product.brand.name
                %tr
                  %th 商品のサイズ
                  %td
                %tr
                  %th 商品の状態
                  %td
                    = @selected_product.status.name
                %tr
                  %th 配送料の負担
                  %td
                    = @selected_product.shippingcost.name
                %tr
                  %th 発送元の地域
                  %td
                    = link_to @selected_product.prefecture.name, "#"
                %tr
                  %th 発送日の目安
                  %td
                    = @selected_product.shipping.name
        - if current_user.present? && current_user.id == @selected_product.saler_id
          .edit-box
            = link_to '商品の編集', edit_product_path(@selected_product.id)
            %p
              or
            = link_to mypage_path(@selected_product.id), id: "del", method: :delete, data: {confirm: "削除しますか？"} do
              = "この商品を削除する"
        .comment-box
          = form_with url: '#', class: "comment-box__new", method: :get, local: true do |form|
            = form.text_area :comment, class: "comment-box__new--body"
            %p.notice-msg
              相手のことを考え丁寧なコメントを心がけましょう。<br>不快な言葉遣いなどは利用制限や退会処分となることがあります。
            = button_tag type: 'submit', class: "comment-box__new--btn" do
              = icon('fa', 'comment')
              = "コメントする"
= render 'products/footer_tmp'