config/routes.rb
Rails.application.routes.draw do

  resources :mypages, only: [:index, :show, :destroy] do
    collection do
      get 'payment_method'
      get 'payment_method/card', to: 'mypages#card_new'
    end
  end

  get 'users', to: 'users#logout'

  resources :categories, only: [:show]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'identifications', to: 'users/registrations#new_identification'
    post 'identifications', to: 'users/registrations#create_identification'

    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :purchases, only: [:index, :create] do
    collection do
      get  'payment_method'
      get  'address'
      get  ':id', to: 'purchases#index'
      post 'pay', to: 'purchases#pay'
      post 'pay/:id', to: 'purchases#pay'
      post 'paymethod_selected'
      get  'payment_method/:id', to: 'purchases#payment_method'
    end
  end

  resources :tops, only: :show
  resources :products, only: [:index]
  resources :registrations, only: [:index]
  root 'products#index'

  resources :products, except: :destroy do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :card, only: :new do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'pay/:id', to: 'card#pay'
      post 'delete', to: 'card#delete'
      get 'card/new/:id', to: 'card#new'
    end
  end

end

app/models/card.rb
class Card < ApplicationRecord
  has_one :payment_selected
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :authenticate_user!

  require "payjp"

  def new
  end

  def pay

    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        description: '登録テスト',
        card: params['payjp-token'],
        metadata: {user_id: current_user.id, email: current_user.email}
      )

      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
    end

    if @card.save
      cards = Card.where(user_id: current_user.id)
      @card_selected = PaymentSelected.find_by(user_id: current_user.id)
      @card_selected.update(card_selected: cards.length, card_id: @card.id)
      @card_selected.save
    else
      redirect_to action: "pay"
    end

    if params[:id].blank?
      redirect_to payment_method_mypages_path
    else
      redirect_to payment_method_purchases_path(id: params[:id])
    end
  end

  def delete

    selected = PaymentSelected.find_by(user_id: current_user.id)

    if selected.card_selected > params[:card_value]
      selected.update(card_selected: selected.card_selected.to_i - 1)
    elsif selected.card_selected == params[:card_value]
      selected.update(card_selected: "0", card_id: "")
    end

    # カード削除
    cards = Card.where(user_id: current_user.id)
    card = cards[params[:card_value].to_i - 1]
    card.delete

    # payjp側の削除
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    customer = Payjp::Customer.retrieve(card.customer_id)
    customer.delete

    if selected.card_selected.blank?
      if params[:params_id].blank?
        redirect_to payment_method_mypages_path
      else
        redirect_to payment_method_purchases_path(id: params[:params_id])
      end
    end

    if params[:params_id].blank?
      redirect_to payment_method_mypages_path
    else
      redirect_to payment_method_purchases_path(id: params[:params_id])
    end
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/_card_new.html.haml
.card
  %section.section-top
    %h2.title クレジットカード情報入力
  %section.form-card
    = form_tag(pay_card_index_path(id: params[:id]), method: :post, id: 'charge-form',  name: "inputForm") do
      .contents
        %section#top-group.group
          %label.group--name カード番号
          %span.group--required 必須
          = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" , maxlength: "16", type: "text", id: "card_number", class: "input--style"
          .image
            = image_tag 'material/card-logo/logo_visa.gif', class: 'img'
            = image_tag 'material/card-logo/logo_mastercard.gif', class: 'img'
            = image_tag 'material/card-logo/saison-logomark.gif', class: 'img'
            = image_tag 'material/card-logo/credit-card-logo-jcb.gif', class: 'img'
            = image_tag 'material/card-logo/amex-logomark.gif', class: 'img'
            = image_tag 'material/card-logo/diners-logomark.gif', class: 'img'
            = image_tag 'material/card-logo/discover-logomark.gif', class: 'img'
        %section.group
          %label.group--name 有効期限
          %span.group--required 必須
          .select-exp
            %select#exp_month{name: "exp_month", type: "text"}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %span#exp-month-span 月
            %select#exp_year{name: "exp_year", type: "text"}
              %option{value: ""} --
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %span#exp-month-span 年
        %section.group
          %label.group--name セキュリティコード
          %span.group--required 必須
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc", class: "input--style"
          .desc
            %p.desc--sentence カード裏面の番号とは？
        #card_token.change
          = submit_tag "登録する", id: "token_submit", class: "change__btn"
          = image_tag 'material/ajax-load.gif', class: "icon_load"
          - if params[:id].blank?
            = link_to "もどる", payment_method_mypages_path, class: "back-button"
          - else
            = link_to "もどる", payment_method_purchases_path(id: params[:id].to_i), class: "back-button"

app/views/card/new.html.haml
= render "purchases/form-header"
.form-wrapper
  .section
    = render "card/card_new"
= render "purchases/form-info"

app/views/card/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_information.last4
%br
- exp_month = @default_card_information.exp_month.to_s
- exp_year = @default_card_information.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
-# = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
-#   %input{ type: "hidden", name: "card_id", value: "" }
-#   %button 削除する