config/routes.rb
Rails.application.routes.draw do

  resources :mypages, only: [:index, :show, :destroy] do
    collection do
      get 'payment_method'
      get 'payment_method/card', to: 'mypages#card_new'
    end
  end

  get 'users', to: 'users#logout'

  resources :categories, only: [:show]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'identifications', to: 'users/registrations#new_identification'
    post 'identifications', to: 'users/registrations#create_identification'

    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :purchases, only: [:index, :create] do
    collection do
      get  'payment_method'
      get  'address'
      get  ':id', to: 'purchases#index'
      post 'pay', to: 'purchases#pay'
      post 'pay/:id', to: 'purchases#pay'
      post 'paymethod_selected'
      get  'payment_method/:id', to: 'purchases#payment_method'
    end
  end

  resources :tops, only: :show
  resources :products, only: [:index]
  resources :registrations, only: [:index]
  root 'products#index'

  resources :products, except: :destroy do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :card, only: :new do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'pay/:id', to: 'card#pay'
      post 'delete', to: 'card#delete'
      get 'card/new/:id', to: 'card#new'
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :saler, class_name: "User"
  belongs_to :category
  has_many :images, dependent: :destroy
  has_one :brand, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :brand, allow_destroy: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :status
  belongs_to_active_hash :shippingcost
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shipping

  validates :name, presence: true
  validates :images, presence: { message: '商品画像がありません'}
  validates :category, presence: { message: 'カテゴリが選択されていません'}
  validates :detail, presence: true
  validates :status_id, presence: true
  validates :prefecture_id, presence: true
  validates :shippingcost_id, presence: true
  validates :shipping_id, presence: true
  validates :price, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :get_category_children, :get_category_grandchildren ]
  before_action :set_product, except: [:index, :show, :new, :create, :get_category_children, :get_category_grandchildren]
  def index
    @new_products = Product.includes(:images).order('created_at DESC').limit(5)
  end

  def show
    @selected_product = Product.includes(:images).find(params[:id])
    @categories = Category.all
  end

  def new
    @product = Product.new
    @product.images.new
    @product.build_brand
    #セレクトボックスの初期値設定
    @category_parent_array = [""]
    # categoriesから親カテゴリーの名前のみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      render new_product_path
    end
  end


  def edit
    @product = Product.find(params[:id])
    @category_parent_array = Category.roots
    @product_root_category = @product.category.root
    @product_children_category = @product_root_category.children
    product_parent_category = @product.category.parent
    @product_grandcildren_category = product_parent_category.children      
  end
  
  def update
    if @product.update(product_params)
      redirect_to root_path
    else
    @category_parent_array = Category.roots
    @product_root_category = Product.find(params[:id]).category.root
    @product_children_category = @product_root_category.children
    product_parent_category = Product.find(params[:id]).category.parent
    @product_grandcildren_category = product_parent_category.children
    render :edit
    end
  end

  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    Category.find("#{params[:parent_id]}").children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    Category.find("#{params[:child_id]}").children
  end

  private

  def product_params
    params.require(:product).permit(:name, :detail, :price, :status_id, :prefecture_id, :category_id, :shippingcost_id, :shipping_id, brand_attributes: [:id, :name], images_attributes: [:image, :_destroy, :id]).merge(saler_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_footer_tmp.html.haml
%aside.appAd
  .inner
    %h2 だれでもかんたんに、人生を変えるフリマアプリ
    %p 今すぐ無料ダウンロード！
  .innerIcon
    = link_to image_tag("material/stricon/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",width: '180', alt: "App画像"), 'https://www.apple.com/jp/app-store/', {class: 'appIcon'}
    = link_to image_tag("material/stricon/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg",width: '180', alt: "Google画像"), 'https://play.google.com/store/apps?hl=ja&gl=US', {class: 'gooIcon'}
.footer-contena
  %ul.conTexts
    %li.conText
      %h2.conText__head FURIMAについて
      %ul
        %li
          = link_to "会社概要(運営会社)", '#', {class: 'linkText'}
        %li
          = link_to "プライバシーポリシー", '#', {class: 'linkText'}
        %li
          = link_to "FURIMA利用規約", '#', {class: 'linkText'}
        %li
          = link_to "ポイントに関する規約", '#', {class: 'linkText'}
    %li.conText
      %h2.conText__head FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧", '#', {class: 'linkText'}
        %li
          = link_to "ブランド一覧", '#', {class: 'linkText'}
    %li.conText
      %h2.conText__head ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイドライン", '#', {class: 'linkText'}
        %li
          = link_to "FURIMAロゴ利用ガイドライン", '#', {class: 'linkText'}
        %li
          = link_to "お知らせ", '#', {class: 'linkText'}
  .footer__logo
    = link_to image_tag("material/logo/logo-white.png",width: '160',  height: '46.34', alt: "FURIMA画像"), root_path, {class: 'appLogo'}
  %p © FURIMA
= link_to new_product_path do
  .cameraBtn
    %span.cameraBtn__text 出品する
    = image_tag 'material/icon/icon_camera.png', width: '54', height: '54' ,alt: 'App画像',  class: 'appIcon'

app/views/products/_head_tmp.html.haml
.header-top
  .header-contena
    .header-contena__top
      %h1.top-icon
        = link_to image_tag('material/logo/logo.png', alt: "FURIMA画像"), root_path, {class: 'a-image'}
      .top-searchBox
        = form_with url: "#" do |f|
          = f.text_field :content, class: 'keyWordFrom', placeholder: 'キーワードから探す'
          %button{type: "submit", class:'keyWordFromBtn'}
            = image_tag 'material/icon/icon-search 1.png', class: 'keyWordFromBtn__icon'
    .header-contena__nav
      %ul.listLeft
        %li.listLeft__item.fastCategory
          = link_to "カテゴリー", '#', {class: 'link-text'}
        %li.listLeft__item
          = link_to "ブランド", '#', {class: 'link-text'}
      %ul.listRight
        - if user_signed_in?
          %li.listRight__login
            = link_to "マイページ", mypages_path, {class: 'link-text'}
        - else
          %li.listRight__new
            = link_to "ログイン", new_user_session_path, {class: 'link-text'}
          %li.listRight__new
            = link_to "新規会員登録", new_user_registration_path, {class: 'link-text'}

app/views/products/edit.html.haml
.product-wrapper
  = form_with model: @product, local: true do |form|
    .product-wrapper__top
      = link_to root_path, class: "corporate-logo" do
        = image_tag 'material/logo/logo.png', class: 'corporate-logo__img'
    .product-wrapper__middle
      .content-01
        .registration-item
          .registration-item__left
            出品画像
          .registration-item__right
            .registration-item__right--color
              必須
        .max-uploads
          最大10枚までアップロードできます
        .uploads
          #uploads-box
          .uploads__icon
            = image_tag 'material/icon/icon_camera.png', class: 'uploads__icon--image'
          .uploads__file
            #image-box
              #previews
                - @product.images.each_with_index do |image, i|
                  = image_tag image.image.url, data: { index: i }, width: '120', height: '130'
              = form.fields_for :images do |image|
                .js-file_group{"data-index": "#{image.index}"}
                  = image.file_field :image, class: 'js-file'
                  %span.js-remove
                    削除
                -if @product.persisted?
                  = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
              -if @product.persisted?
                .js-file_group{"data-index" => "#{@product.images.count}"}
                  = file_field_tag :image, name: "product[images_attributes][#{@product.images.count}][image]", class: 'js-file'
                  %span.js-remove
                    削除
              - if @product.errors.include?(:images)
                %p.error-text
                  = @product.errors.messages[:images][0]
                    
      .content-02
        .registration-item
          .registration-item__left
            商品名
          .registration-item__right
            .registration-item__right--color
              必須
        .input-string
          = form.text_field :name, class: 'input-string__form', maxlength: 11, placeholder: 'type a message'
          - if @product.errors.include?(:name)
            %p.error-text
              = @product.errors.messages[:name][0]
        .registration-item
          .registration-item__left
            商品の説明
          .registration-item__right
            .registration-item__right--color
              必須
        .input-text
          = form.text_area :detail, class: 'input-text__form', maxlength: "1000", placeholder: "商品の説明（必須 1,000文字以内);(色、素材、重さ、定価、注意点など)     例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
          - if @product.errors.include?(:detail)
            %p.error-text
              = @product.errors.messages[:detail][0]
        .count-length
          0/1000
      .content-03
        .title-03
          商品の詳細
        .registration-item
          .registration-item__left
            カテゴリー
          .registration-item__right
            .registration-item__right--color
              必須
        .input-string
          .input-string__category
            = form.collection_select :category_id, @category_parent_array, :id, :name, { prompt: '選択してください', selected: Product.find(params[:id]).category.parent.parent.id}, {class: 'input-string__category--form', id: 'parent-category'}
            #child-wrapper.input-string__category
              = form.collection_select :category_id, @product_children_category, :id, :name, {selected: Product.find(params[:id]).category.parent.id}, {class: 'input-string__category--form'}
              #grandchild-wrapper.input-string__category
                = form.collection_select :category_id, @product_grandcildren_category, :id, :name, {selected: Product.find(params[:id]).category.id}, {class: 'input-string__category--form'}
          - if @product.errors.include?(:category)
            %p.error-text
              = @product.errors.messages[:category][1]
        .registration-item
          .registration-item__left
            ブランド
          .registration-item__rightgray 
            .registration-item__rightgray--gray
              任意
        .input-string
          = form.fields_for :brand do |brand|
            = brand.text_field :name, placeholder: "例）シャネル", value: "", class: 'input-string__form'
        .registration-item
          .registration-item__left
            商品の状態
          .registration-item__right
            .registration-item__right--color
              必須
        .input-string
          = form.collection_select :status_id, Status.all, :id, :name, {include_blank: "選択してください"}, {class: 'input-string__form'}
          - if @product.errors.include?(:status_id)
            %p.error-text
              = @product.errors.messages[:status_id][0]
      .content-04
        .title-box
          .title-box__title04
            配送について
          .title-box__question
            =icon('fas','question-circle')
        .registration-item
          .registration-item__left
            配送料の負担
          .registration-item__right
            .registration-item__right--color
              必須
        .input-string
          = form.collection_select :shippingcost_id, Shippingcost.all, :id, :name, {include_blank: "選択してください"}, {class: 'input-string__form'}
          - if @product.errors.include?(:shippingcost_id)
            %p.error-text
              = @product.errors.messages[:shippingcost_id][0]
        .registration-item
          .registration-item__left
            発送元の地域
          .registration-item__right
            .registration-item__right--color
              必須
        .input-string
          = form.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: "選択してください"}, {class: 'input-string__form'}
          - if @product.errors.include?(:prefecture_id)
            %p.error-text
              = @product.errors.messages[:prefecture_id][0]
        .registration-item
          .registration-item__left
            発送までの日数
          .registration-item__right
            .registration-item__right--color
              必須
        .input-string
          = form.collection_select :shipping_id, Shipping.all, :id, :name, {include_blank: "選択してください"}, {class: 'input-string__form'}
          - if @product.errors.include?(:shipping_id)
            %p.error-text
              = @product.errors.messages[:shipping_id][0]
      .content-05
        .title-box
          .title-box__title04
            価格（¥300〜9,999,999）
          .title-box__question
            =icon('fas','question-circle')
        .price-box
          .price-box__left
            .registration-item
              .registration-item__left
                販売価格
              .registration-item__right
                .registration-item__right--color
                  必須
          .price-box__right
            .coin-box
              .coin-box__left
                ¥
              .coin-box__right
                = form.text_field :price, class: 'coin-box__right--input', placeholder: '0'
                - if @product.errors.include?(:price)
                  %p.error-text
                    = @product.errors.messages[:price][0]
        .margin-box
          .margin-box__left
            販売手数料（10%）
          .margin-box__right
            ー
        .salesprofit-box
          .salesprofit-box__left
            販売利益
          .salesprofit-box__right
            ー
        .register-btn
          = form.submit '変更する', class: 'register-btn__product'
        .save-btn
          = link_to mypage_path, class: 'save-btn__cancel' do
            キャンセル
      .product-wrapper__bottom
        .policy-box
          .policy-box__left
            プライバシーポリシー
          .policy-box__center
            フリマ規約
          .policy-box__right
            特定商取引に関する表記
        .corporate-logo-white
          = link_to root_path do
            = image_tag 'material/logo/logo-white.png', class: 'corporate-logo-white__img'
        .corporate-inc
          @Furima.Inc.

app/views/products/index.html.haml
.topWrapper
  = render 'head_tmp'

  .main
    %section.mainVisual
      .content
        %h2.subTitle
          人生を変えるフリマアプリ
        %p.contentText
          FURIMAはだれでもかんたんに出品・購入できる
          %br
          フリマアプリです。
        .contentbtn
          = link_to image_tag("material/stricon/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",width: '180', alt: "App画像"), 'https://www.apple.com/jp/app-store/', {class: 'app-btn'}
          = link_to image_tag("material/stricon/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg",width: '180', alt: "Google画像"), 'https://play.google.com/store/apps?hl=ja&gl=US', {class: 'app-btn'}


    %section.usage
      %h2.reasonText
        FURIMAが選ばれる3つの理由
      %ul.reasonImageLists
        %li.reasonImageList
          .listImg
            %span.number 1
            = image_tag 'material/pict/pict-reason-01.jpg', class: 'reasonimg'
          .listText
            %span.text 3分
            ですぐに出品
          %p.listDescription
          スマホで入力するだけで簡単に出品で 
          %br
          きる！
        %li.reasonImageList
          .listImg
            %span.number 2
            = image_tag 'material/pict/pict-reason-02.jpg', class: 'reasonimg'
          .listText
            %span.text シンプル
            で使いやすい
          %p.listDescription
          めんどくさい入力は必要なく、検索も
          %br
          購入もスムーズ！
        %li.reasonImageList.list-last
          .listImg
            %span.number 3
            = image_tag 'material/pict/pict-reason-03.jpg', class: 'reasonimg'
          .listText
            手数料
            %span.text 業界最安値
          %p.listDescription
          最大3%でお得に出品＆購入！


    %section.ad
      .ad__DIinnre
        %h2.ad__DIinnre--title
          会員数日本一
        %p.ad__DIinnre--text
          FURIMAは、フリマアプリで最も人気。
          %br
          出品・購入回数も凝塊最多です！
          %br
          ほしかったあの商品に出会えるかもしれません。
        .contentbtn
          = link_to image_tag("material/stricon/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",width: '180', alt: "App画像"), 'https://www.apple.com/jp/app-store/', {class: 'app-btn'}
          = link_to image_tag("material/stricon/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg",width: '180', alt: "Google画像"), 'https://play.google.com/store/apps?hl=ja&gl=US', {class: 'app-btn'}

    %section.description
      %h2.description__text
        FURIMAの特徴
      .description__items
        %section.item
          .item__img
            = image_tag 'material/icon/icon-01.png', class: 'item__img--icon'
          %h3.itemTitl
            簡単に売り買いできる
          %P.itemDetail
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        %section.item
          .item__img
            = image_tag 'material/icon/icon-03.png', class: 'item__img--icon'
          %h3.itemTitl
            売上金は即日振込みに対応
          %p.itemDetail
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        %section.item
          .item__img
            = image_tag 'material/icon/icon-04.png', class: 'item__img--icon'
          %h3.itemTitl
            様々な支払いに対応
          %p.itemDetail
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

    %section.pickupContainer
      %h2.head
        ピックアップカテゴリー
      .productBOX
        .productHead
          = link_to "新規投稿商品", '#', {class: 'productHead__text'}
        .productLists
          - @new_products.each do |product|
            .productList
              = link_to product_path(product), {class: 'productList__link'} do
                .productList__img
                  - if product.buyer_id.present?
                    .productList__img--sold-box
                    %p.productList__img--sold-text
                      SOLD
                  = image_tag product.images[0].image.url, alt: "image_url", class: 'productImg'
                .productList__body
                  %h3.name
                    = product.name
                  .details
                    %ul 
                      %li
                        = product.price
                        円
                      %li 
                        = icon('fa', 'star')
                        1
                    %p.tax (税込)
    %section.pickupContainer.last-child
      %h2.head
        ピックアップブランド
      .productBOX
        .productHead
          = link_to "新規投稿商品", '#', {class: 'productHead__text'}
        .productLists
          - @new_products.each do |product|
            .productList
              = link_to product_path(product), {class: 'productList__link'} do
                .productList__img
                  - if product.buyer_id.present?
                    .productList__img--sold-box
                    %p.productList__img--sold-text
                      SOLD
                  = image_tag product.images[0].image.url, alt: "image_url", class: 'productImg'
                .productList__body
                  %h3.name
                    = product.name
                  .details
                    %ul 
                      %li
                        = product.price
                        円
                      %li 
                        = icon('fa', 'star')
                        1
                    %p.tax (税込)
    = render 'footer_tmp'

app/views/products/show.html.haml
.show-top
  = render 'head_tmp'
.show-wrapper
  .show-main
    .contents
      .top-content
        .product
          %h2.product__name
            = @selected_product.name
          .product__body
            %ul
              %li
                = image_tag @selected_product.images[0].image.url
                %ul
                  - @selected_product.images.each_with_index do |productimage|
                    %li
                      = image_tag productimage.image.url
          .product__price
            %span
              ¥
              = @selected_product.price
            .product__price--detail
              (税込)送料込み
          - if @selected_product.buyer_id.present?
            .product__sold
              = "売り切れました"
          - elsif current_user.present? && current_user.id != @selected_product.saler_id
            = link_to purchases_path(id: @selected_product.id), class: "product__purchase" do
              = "購入画面に進む"
          - elsif current_user.present? && current_user.id == @selected_product.saler_id
          - else
            = link_to new_user_session_path, class: "product__purchase" do
              = "購入画面に進む"
          .product__description
            = @selected_product.detail
          .table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td
                    = @selected_product.saler.nickname
                %tr
                  %th カテゴリー
                  %td
                    - @categories.each do |grandchildren|
                      - if @selected_product.category_id == grandchildren.id
                        = link_to category_path(grandchildren.parent.parent.id) do
                          = grandchildren.parent.parent.name
                          %br
                        = link_to category_path(grandchildren.parent.id) do
                          = grandchildren.parent.name
                          %br
                        = link_to category_path(grandchildren.id) do
                          = grandchildren.name
                          %br
                %tr
                  %th ブランド
                  %td
                    = @selected_product.brand.name
                %tr
                  %th 商品のサイズ
                  %td
                %tr
                  %th 商品の状態
                  %td
                    = @selected_product.status.name
                %tr
                  %th 配送料の負担
                  %td
                    = @selected_product.shippingcost.name
                %tr
                  %th 発送元の地域
                  %td
                    = link_to @selected_product.prefecture.name, "#"
                %tr
                  %th 発送日の目安
                  %td
                    = @selected_product.shipping.name
          .optional-area
            %ul.like
              %li.like-btn
                = icon('fa', 'star')
                お気に入り1
            %ul.report
              %li.report-btn
                = link_to "#" do
                  = icon('fa', 'flag')
                  = "不適切な商品の通報"
        .comment-box
          = form_with url: '#', class: "comment-box__new", method: :get, local: true do |form|
            = form.text_area :comment, class: "comment-box__new--body"
            %p.notice-msg
              相手のことを考え丁寧なコメントを心がけましょう。<br>不快な言葉遣いなどは利用制限や退会処分となることがあります。
            = button_tag type: 'submit', class: "comment-box__new--btn" do
              = icon('fa', 'comment')
              = "コメントする"
      %ul.links
        %li
          = link_to "#" do
            = icon('fa', 'angle-left')
            %span
              = "前の商品"
        %li
          = link_to "#" do
            %sapn
              = "後の商品"
            = icon('fa', 'angle-right')
      .related-items
        = link_to '#' do
          = @selected_product.saler.nickname
          さんのその他の出品
        .related-items__lists
          .related-items__lists__product
            = link_to "#" do
              %figure.related-items__lists__product--img
                = image_tag 'material/pict/a001.png'
              .related-items__lists__product--body
                %h3.product-name product1
                .product-price
                  %ul
                    %li
                      1000円
                    %li
                      = icon('fa', 'star')
                      1
                  %p
                    （税込）
  = render 'footer_tmp'